### ISSUE TITLE
digitalRead function does not work with Arduino virtual button

### ISSUE THREAD

**Issue by bgaultier** [France-ioi/codecast#62] opened 2017-06-01 18:08 UTC
The following Arduino code does not work (we never enter the if) :

![capture d ecran 2017-06-01 a 20 06 12](https://cloud.githubusercontent.com/assets/177940/26693912/15da5cf0-4706-11e7-84e6-4a034f1c2dc9.png)

**Comment by epixode** [comment] 2017-06-02 07:12
I think this is a duplicate of #60, can you please test and confirm?

**Comment by bgaultier** [comment] 2017-09-22 09:35
Hey @epixode and @mathias-hiron , 
Students on our current MOOC "Programmer avec Arduino" are having the same issue that the digitalRead function. Please have a look at the log below : 

![capture d ecran 2017-09-22 a 11 34 03](https://user-images.githubusercontent.com/177940/30738371-2101995e-9f8a-11e7-932f-742c11a9c2b6.png)

**Comment by mathias-hiron** [comment] 2017-09-27 08:56
It's fixed, thanks!

**Closed** 2018-02-21 13:43 UTC
Labels: duplicate
