### ISSUE TITLE
Memory representation for linked lists

### ISSUE THREAD

**Issue by petraBT** [France-ioi/codecast#99] opened 2018-02-28 16:31 UTC
The following code executes just fine, but the memory representation and variable editor don't appear to work:

#include <stdio.h>
#include <stdlib.h>
struct point{
	int x;
	int y;
	struct point *next;
};

int main(void) {
    //! showMemory(start=65520)
	struct point pt1 = {1, 2, NULL};
	struct point pt2 = {-2, 3, NULL};
	struct point pt3 = {5, -4, NULL};
	struct point *ptr;
	
	ptr = &pt1;
	pt1.next = &pt2;
	pt2.next = &pt3;
	
	while (ptr!=NULL) {
	    printf("(%d, %d)\n", ptr->x, ptr->y);
	    ptr = ptr->next;
	}
	return 0;
}

**Comment by epixode** [comment] 2018-02-28 16:46
Duplicate of https://github.com/France-ioi/codecast/issues/97 fixed on /next, please reload the page ☺

**Closed by epixode** 2018-02-28 16:46 UTC
Labels: duplicate

**Comment by petraBT** [comment] 2018-02-28 16:58
Beautiful!!! Thank you!!
