### ISSUE TITLE
initializing an array at declaration time faulty in v5

### ISSUE THREAD

**Issue by petraBT** [France-ioi/codecast#81] opened 2018-02-07 21:32 UTC
Initializing an array at declaration time does not work properly as the following screenshots (taken during step-by-step execution) show:
<img width="911" alt="screen shot 2018-02-07 at 4 25 15 pm" src="https://user-images.githubusercontent.com/33522257/35942696-7f9f4e50-0c24-11e8-988e-b6e9d54c355b.png">
<img width="851" alt="screen shot 2018-02-07 at 4 27 28 pm" src="https://user-images.githubusercontent.com/33522257/35942710-8a2725d2-0c24-11e8-847d-200388da57a9.png">

**Comment by epixode** [comment] 2018-02-12 21:43
Petra,
I seem to be unable to reproduce this issue in /v5 with a simple program that just puts a 10-ints array on the stack.  Can you post a full program (or recording) that demonstrates the incorrect behavior you have experienced?
Thank you in advance!

**Comment by remisharrock** [comment] 2018-02-12 22:07
me neither, 
by the way when I do the step by step execution before executing int n = 10; I cannot see the entire list in the variables:
![image](https://user-images.githubusercontent.com/8048877/36122398-3033a888-1017-11e8-86d4-614d9c66f826.png)

**Comment by petraBT** [comment] 2018-02-12 22:39
Here is a codecast that shows the issue: https://codecast.france-ioi.org/v5/player?base=https%3A%2F%2Ffioi-recordings.s3.amazonaws.com%2Fdartmouth%2F1518475124087

Let me know if you need more information!

**Comment by epixode** [comment] 2018-02-12 22:45
Petra, when I load your recording I notice a comma is missing between 18 and -10, which equals 8 and explains the behavior.

The screenshot you posted above could be caused by an editor problem, where the source code buffer was not maintained properly during recording, resulting in executing a program that is different from the source code being displayed.

I'll think about this a little more and go through the code to see if I can explain what happened.

**Comment by petraBT** [comment] 2018-02-12 22:51
Oh my gosh - that was it! I can't believe it... Sorry!

**Comment by mathias-hiron** [comment] 2018-02-12 22:56
Dear Remi,

not being able to see the entire lists is by design: we limit it to two lines.

Imagine what would happen otherwise if you had a program with an array size 1000. For displaying arrays completely, you can use the array visualization directive.

**Comment by remisharrock** [comment] 2018-02-12 22:56
https://github.com/France-ioi/codecast/issues/81#issuecomment-365079256 
Is it the desired behavior to have a limitation of two lines in the variables on the left ? 
Maybe ?

**Comment by remisharrock** [comment] 2018-02-12 22:56
@mathias-hiron got it! thanks 👍

**Comment by remisharrock** [comment] 2018-02-12 22:57
Good so I guess this is not an issue anymore and we can close it !

**Comment by epixode** [comment] 2018-02-12 22:57
No worry Petra, I also got confused looking at Rémi's correct program.  I'm glad there isn't a subtle bug with editor buffer recording!

**Closed by epixode** 2018-02-12 22:57 UTC
